### ISSUE TITLE
Highlight operated elements

### ISSUE THREAD

**Issue by yoavst** [A9T9/RPA#1]
iMacros for both Chrome, Firefox and internet explorer allows by default to highlight the elements on which it operates. 

Can you add highlighting feature? 
If can help with implementing it.

**Comment by A9T9** [comment]
Good idea! That is useful and will be added asap. 

For manually testing (highlighting) there is already the "Select" button. You select a line from the macro, click "Select" and the element is highlighted.

**Comment by yoavst** [comment]
So it seems like everything is built in, just need to call it from the player, great to hear!

**Comment by A9T9** [comment]
Done with V0.8, see https://a9t9.com/kantu/web-automation/chrome/whatsnew
