### ISSUE TITLE
Missing texts

### ISSUE THREAD

**Issue by Tyrben** [A9T9/RPA#100]
In English, some texts are displayed with their internal value (with exclamation point)

Version: 6.2.6
Browser: Firefox 89.0 (64bits)
OS: Windows

- !TIMEOUT_PAGELOAD
- !TIMEOUT_WAIT
- !TIMEOUT_MACRO
- !TIMEOUT_DOWNLOAD

**Comment by A9T9** [comment]
I am not sure I understand this issue. Can you please add a screenshot?

**Comment by A9T9** [comment]
Closing until more info
