### ISSUE TITLE
Operation in Iframe

### ISSUE THREAD

**Issue by spiderpug** [A9T9/RPA#2]
Currently it does not work to run scripts in an embedded iframe.

My current problem is that I want to interact with a video player that embeds itself using an Iframe in the parent page. Couldn't find a way to select elements in there. It seems to work in the top frame only.

Is there a workaround for my problem?

**Comment by A9T9** [comment]
> It seems to work in the top frame only.

Yep, that is a known limitation of V0.5. The good news is that frame/iframe support is scheduled for the next update already.

There is no workaround (that we know of) with Kantu for Chrome. But if you are on Windows you can use the free [Kantu Web Automation](https://a9t9.com/kantu/web-automation/) software. It works [visually with screenshots of the rendered browser image](https://a9t9.com/kantu/web-automation/chrome#faq).

**Comment by A9T9** [comment]
Done with V0.8, see https://a9t9.com/kantu/web-automation/chrome/whatsnew
