### ISSUE TITLE
How to run multiple test cases?

### ISSUE THREAD

**Issue by hukadev** [A9T9/RPA#23]
Hi guys,

Can I run multiple test cases like test suite?

Regards.
Huka

**Comment by A9T9** [comment]
The "test suite" feature will be available with the next update...  => if all goes well next week already. We are working on it right now  ;-)

**Comment by hukadev** [comment]
Hi, @A9T9 

That's awesome! :)

**Comment by erikandershed** [comment]
Hi, @A9T9 

Any idea when this awesome function will arrive?

**Comment by A9T9** [comment]
There have been some delays but we still aim to have it ready in November.

**Comment by A9T9** [comment]
Just FYI: Test suites did not make it in the November release, but it is now on the top of the list for the December update.

**Comment by A9T9** [comment]
Test Suite support arrived with V2.2.0!

For details, see https://a9t9.com/kantu/web-automation/chrome#testsuites

**Comment by hukadev** [comment]
Hi @A9T9 
Thanks for your efforts!
