### ISSUE TITLE
"Execute this command" doesn't work

### ISSUE THREAD

**Issue by CarolineRodrigues** [A9T9/RPA#24]
When I do a right click above a command and click "Execute this command" nothing happen. And on console have javascript erros.
![image](https://user-images.githubusercontent.com/31484196/33370331-2359986a-d4ef-11e7-9a71-6ff5c683a08f.png)
![image](https://user-images.githubusercontent.com/31484196/33370364-372ef68c-d4ef-11e7-8cc6-254e842bed42.png)

**Comment by A9T9** [comment]
I confirmed the issue (same problem with "Run from here"). It will be fixed with the next update (planned for next week)

**Comment by A9T9** [comment]
This is now fixed with V2.2.0
