### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by senpl** [A9T9/RPA#26]
Current version not have option to display data in dark theme. This option seems easy to implement. I think any sort of options/preferences also would be nice to have.

**Comment by A9T9** [comment]
Hmm... just to clarify what you mean with display data in dark theme: You mean white text on black background, like with the Atom editor https://atom.io/ ?

**Comment by senpl** [comment]
yes. Exactly that.

**Comment by A9T9** [comment]
Closing for now (no enough "upvotes")
