### ISSUE TITLE
Make it accessible from DevTools to support Electron

### ISSUE THREAD

**Issue by elcreator** [A9T9/RPA#3]
It will be good feature

**Comment by A9T9** [comment]
Sounds interesting, but I have no idea what is the connection between the Electron framework and a Chrome extension. If you or anyone else can provide more details, that would be appreciated.

**Comment by elcreator** [comment]
Electron framework supports majority of Chrome extensions "as is", you don't need to learn about Electron. Only thing you need is to make it a tab in Developer Tools, not only button. It will be useful for Chrome users too. Please see manual here https://developer.chrome.com/extensions/devtools and examples of developer tools extensions here https://developer.chrome.com/devtools/docs/extensions-gallery .

**Comment by A9T9** [comment]
very interesting, thanks for the info!

**Comment by A9T9** [comment]
This feature request received no additional vote for more than 6 months, so I am closing it for now.

**Comment by rbaffoe** [comment]
Would like to reopen this request. Can I contribute to get this implemented?

**Comment by A9T9** [comment]
>  Can I contribute to get this implemented?

Sure :)

**Comment by A9T9** [comment]
Closing this for now, but of course, pull requests are welcome.
