### ISSUE TITLE
Feature: Ability to add Comments \ Annotate

### ISSUE THREAD

**Issue by cwpm** [A9T9/RPA#31]
Like the original Selenium IDE for FF. Having ability to add Comments to annotate an area \ section of the script. 

Some scripts can be quite lengthy and to aid collaboration and revisiting it's a good way to quickly identify what that section does. With your IF \ ELSE rules it'd be good to annotate what the rule is and why. 
I believe it'd be a welcome addition, all other versions of new Selenium in progress are yet to re-introduce this feature.

**Comment by A9T9** [comment]
Totally agree... the feature is on our March todo list already

**Comment by cwpm** [comment]
Fantastic news :-D 
Will the Comments be a different colour(s) so they are easier to spot?

**Comment by cwpm** [comment]
Hello there.

I've seen the new Comment command in Kantu. Can this be represented visually different e.g. in colour?
In the original Selenium it was in purple, as such easier to see the Comment and broke up the script. 

If you want to go a step further and give a colour option then great. But just having a different colour to so it's visually different helps.
