### ISSUE TITLE
Feature: NotAttribute, Text\ElementNotPresent

### ISSUE THREAD

**Issue by cwpm** [A9T9/RPA#32]
New Feature. In the past there were requirements to add a detection to check that a value \ script \ attribute \ text isn't present on websites.  

We usually have a TextNotPresent to rule out bad characters, and NotAttribute to detect NoIndex,NoFollow isn't set on websites. I presume it's possible to do an ELSE or IF to accommodate this situation but it leads to writing further commands
A straight forward NotAttribute, TextNotPresent or ElementNotPresent would be quicker and less entries to include. This was present in the old Selenium IDE FF version.

Could this be considered?

**Comment by cwpm** [comment]
Thank you for the feedback via e-mail

> "NOT" commands: As you guessed, inverting a command  with "if" is quite easy - and more flexible then the old "not" versions of the commands:

verifyChecked | id=xxx
if | {!lastCommandOk}
ECHO | “element is NOT CHECKED” | red
endif

Need to work on IF and ENDIF for each NotAttribute. I'll look to work that in.

**Comment by A9T9** [comment]
In addition, the last upgrade brings the [ThrowError ](https://a9t9.com/kantu/docs/webextensions/selenium-ide#throwerror) command. This allows you stop the macro, just like an AssertNot... would do.

verifyChecked | id=xxx
if | {!lastCommandOk}
ThrowError  “element is NOT CHECKED” 
endif

**Comment by A9T9** [comment]
We might still add the whole family of ...NOT... commands, but are unsure. Feedback if they are really needed, or if the if/endif solution works, is welcome.

**Comment by cwpm** [comment]
I'll vote 👍

**Comment by A9T9** [comment]
Closing this, as we use the [forum ](https://forum.a9t9.com/) now to track feature request.
