### ISSUE TITLE
Feature: Detecting Google Analytics tracking UA \ code and other scripts

### ISSUE THREAD

**Issue by cwpm** [A9T9/RPA#33]
This is a new Feature, one that wasn't possible in the old Selenium IDE but is worth a mention as it's a common requirement for most sites to have a Google Analytics for tracking visitors. And there are also other scripts which get added along the way.

On a QA check of ensuring the script or Google UA is present along with other tracking scripts is becoming more crucial in the fast development world. If there was a way to detect part of a script such as a Google Analytics tracking code or remarketing tag. It would be a good feature and benefit.

I don't believe this is currently in any Selenium version, but would be considered an asset to have in my opinion as I work in the e-commerce world and checking for each script at each stage can be time consuming on a fast paced development. Having this would reduce time significantly.

**Comment by cwpm** [comment]
Thank you for the reply via e-mail,

> The comment option and a SEARCH (html source code) command (e. g. for testing on GA code) will be available with the Kantu March update.

Much appreciated.

**Comment by cwpm** [comment]
I've seen the sourceSEARCH but don't know how to use it as such.

Command: sourceSearch
**Target:** what do I put in here to target a Google Analytics code? I put in the UA-XXXX code but nothing
**Value:**  same for this. 

Any instructions to use this feature?

**Comment by A9T9** [comment]
sourceSearch is not fully implemented yet.  But it will be with the next update in a few days. Then this will work:
```
sourceSearch | UA-12345 | $var
If  | $var == 0 |
ThrowError ("Google Analytics id not found!")
endIf
```
$var contains the number of times  that the string has been found.

**Comment by A9T9** [comment]
Now released! => See https://a9t9.com/kantu/docs/webextensions/selenium-ide/sourceextract-sourcesearch
