### ISSUE TITLE
Feature: WaitForVisible \ VerifyVisible?? Issues on Forms \ One Page checkouts of pre-loaded elements

### ISSUE THREAD

**Issue by cwpm** [A9T9/RPA#34]
I've been testing this on websites that have Forms \ One Page checkouts and I've been having the same issues with the AssetElementPresent and VerifyElementPresent as I did on the original Selenium IDE.

One some Forms and One Page checkouts all the elements are loaded already so when it hits VerifyElementPresent, it is already present on the page but it's hidden and not displaying yet. This tricks the script to keep running many steps ahead whilst the Frontend is still trying to load the last step.

In the past, to overcome this, you had to use WaitForVisible was used which we replaced the ElementPresent commands. In essence, they do very similar jobs but for WaitForVisiible the element will have to be loaded and also Visible on the Frontend for it then to action. 

Not sure if you want a New Command, or to update your Existing Verify\AssetElementPresent.
For me, it's very crucial as otherwise many scripts don't run 100% accurately and causes alot of reviewing Errors that aren't errors.

**Comment by A9T9** [comment]
Hi, do you happen to have or know a good test page where we can recreate this problem?

> ...or to update your Existing Verify\AssetElementPresent.

Our guess at the moment is that 99% of AssetElementPresent users actually mean "visible", would you agree to that? If so, "upgrading" AssetElementPresent to actually mean present and visible makes good sense.

If you just want to check something in the HTML code, the upcoming SEARCH command can do that (see #33  )

**Comment by cwpm** [comment]
I do indeed, quite a few e-commerce sites have the steps pre-loaded but not visible.
Examples of these are on:
Snooper - https://gb.snooper.eu
Christy - http://www.christy.co.uk/

Add a product to Basket, and when you get to the Checkout (first step is Billing details). That is a One Page checkout, each stage is pre-loaded but the next stage will only show visible when you progress, and that's where the WaitForVisible comes in very handy.
It's also the case for most items as they get loaded first, then made visible.

Yes I would agree that 99% of the users mean Present and Visible for the AssertElementPresent, one command for them both makes sense.

**Comment by cwpm** [comment]
I see that there is a WaitForVisible command now in Kantu.
Not having this combined with AssetElementPresent anymore then? I can give it a look over and test soon enough.

**Comment by A9T9** [comment]
Updated with V2.7.3. Now [click ](https://a9t9.com/kantu/docs/webextensions/selenium-ide/click) waits for the element to appear **and** become visible. In most cases this is the right thing to do, but not always. 

You can disable this by setting the [waitForVisible ](https://a9t9.com/kantu/docs/webextensions#!waitforvisible) internal variable to false.

AssetElementPresent does (as the name says) "just" checks for presence. It can be combined with WaitForVisible  to assert the element is visible.
