### ISSUE TITLE
 Lack of new version in github and releases

### ISSUE THREAD

**Issue by generalov** [A9T9/RPA#36]
New version of Kantu in Chrome is 2.6.0. Here only 2.3.0 is present.
It should not be hard to up-to-date version in github, so anyone could improve new features.
Thanks for all great work.

**Comment by Jongkeun** [comment]
That's what I'm saying @generalov .
I wish to get a recent updated project.

**Comment by A9T9** [comment]
The latest GPL3 version of Kantu is V2.3.0 - there is a delay for the new version as we _might_ change its license. Nothing is decided yet. But if this delay is causing any problems for you, please email us at team@a9t9.com to discuss. Just mention this ticket in your email. We are looking forward to getting feedback on what is the best license going forward.

For more information about the Kantu dual license see https://github.com/A9T9/Kantu-for-Chrome/blob/master/COPYRIGHT
