### ISSUE TITLE
Beta Testers wanted! 

### ISSUE THREAD

**Issue by A9T9** [A9T9/RPA#39]
Are you interested in becoming a Kantu beta tester?

As beta tester, we will email you (hidden) install links for new Kantu versions before they go live in Chrome store. **Beta versions never overwrite a regular Kantu version**. The beta channel is technically a separate extension with its own toolbar button. We will email you once a new version is available so you can grab it. So beta-testing Kantu does not interfere with your regular Kantu projects and macros. 

**If you are interested in helping out, please sign-up here:**
http://eepurl.com/dm0cTX

The link goes to a Mailchimp signup form.

**Comment by generalov** [comment]
Hi @A9T9, Thank you so much for the awersome chrome extension! I'll really happy to help you with testing and developing new features if you could keep the souce code up to date on GitHub. Again, your GPLv3 licence requires to disclose souce code for distributed software and its derivatives.

**Comment by A9T9** [comment]
Hi @generalov I updated #36 to clarify the reason for the delay. If this is causing any problems for you please email us at team@a9t9.com to discuss.

**Comment by vikramvi** [comment]
@A9T9 thanks for your efforts with Selenium IDE alternative but I found much better one katalon.com/resources-center/blog/katalon-automation-recorder/, I suggest you join hands with katalon team instead of duplicating efforts. IMHO

**Comment by A9T9** [comment]
@vikramvi  Katalon is **not** open-source, even so they started as Sideex clone. This is legal, but not fair to the open-source community if you ask me. They are not giving back. And now they are copying Kantu features :-)

Why do you think Katalon is better?

**Comment by vikramvi** [comment]
@A9T9 apologies if you felt offended, being Selenium user from 2006; I found Katalon design ( UI, UX ) is matching with that of Selenium IDE with all its basic features included as well.

This will help old timers of IDE to shift quickly. 

If you see I had filed few issues with your tool about feature/s requests few months back.

Also please check reviews chrome.google.com/webstore/detail/katalon-recorder-selenium/ljdobmomdgdljniojadhoplhkpialdid/reviews, so find out what  is liked/disliked by community.

Anyways thanks for your efforts.

**Comment by A9T9** [comment]
No offense at all! Critical feedback is always very welcome here. But if a pure Selenium IDE experience is what you are looking for, I recommend the new Selenium IDE from the core team. Even so the Katalon IDE is more feature complete for now, I do not like that they take tons of open-source but do not give back. (For this reason I also removed the link in your post).
