### ISSUE TITLE
When running locally, can't find background.js

### ISSUE THREAD

**Issue by ozymandias547** [A9T9/RPA#4]
When I try to develop, I get the following error:
![image](https://user-images.githubusercontent.com/2013007/29733433-b16c9004-89b2-11e7-9683-cec0bfa6bcdf.png)

**Comment by A9T9** [comment]
It is open-source and the full code is right here on Github. The code for the background page is at https://github.com/A9T9/Kantu-for-Chrome/blob/master/src/ext/bg.js

Note that you need to build the extension first using this command line:

run `npm i `, then `npm run build`

Once done, the ready-to-use extension code appears in the **/dist** directory
