### ISSUE TITLE
Kantu consumes more and more RAM which makes it slower and slower

### ISSUE THREAD

**Issue by schuesslerf** [A9T9/RPA#40]
Hello,

I'm using Kantu for some web automation.

In my program itself, there is a infinite loop, built with a lable and a goto, so something like:

```
label: start
*some code*
goto: start
```

In the code part, there are some variable declarations (most of them are `storeEval`).

Now as I said, the execution is getting slower and slower, you can clearly see that from 3 times per second its going like one time in 3 seconds.

Whats interesting is, that in Chrome Taskmanager (Shift + ESC), the Kantu RAM usage is going higher and higher. Whenever I stop the script, close Kantu and reopen it and start the script again, its fine again, so then it is again 3 times per second.

So it seems like the longer Kantu runs, the higher the RAM usage is. And it doesn't seem to set it back automatically.

One thing I was thinking of is, that it might create a new variable for every storeEval, even if it is the same variable name? Does this sound logical? Might this be? If yes, would I be able to change it? If not, what else could be the problem? Another thing I was thinking of is the logs, in the Kantu Window, there are logs, which never get cleared automatically. Clearing those logs frees RAM, making the script faster as well. Is there any way to automatically delete the logs or to don't log at all?

A test confirmed my feeling that it's getting slower.

With `!runtime` in the first loop, it took 0.07 seconds, in the loop no. 956, it took 0.15 seconds and its getting more and more, I just left the script runnning for about 8 hours now, RAM usage went from 800MB to about 3GB, which really shouldn't be like that.

Any ideas, what to do?

**Comment by A9T9** [comment]
>Is there any way to automatically delete the logs or to don't log at all?

Not yet, but this is on our todo list for the March update

>So it seems like the longer Kantu runs, the higher the RAM usage is. And it doesn't seem to set it back automatically.

I confirmed the issue and we will fix this as well.

**Comment by schuesslerf** [comment]
Okay, will you comment again, after you fixed it?

**Comment by A9T9** [comment]
Yes. I will comment and close the ticket once it is done

**Comment by A9T9** [comment]
This issue should have been solved by now. If you still have memory issues, please re-open.
