### ISSUE TITLE
Error to import JSON property 'map' 

### ISSUE THREAD

**Issue by pdasilvagxc** [A9T9/RPA#41]
Hi, How are you?

After export a Test Suit and later I try to import, it shows me the error: '[error]
in parsing suite_XXXXX.json: Cannot read property 'map' of undefined'.  How can I define de map of the Test Suites?

**Comment by A9T9** [comment]
Can you please send (attach) such a corrupted export to this ticket?

**Comment by pdasilvagxc** [comment]
Thanks for the contact, today I could export and import de test Suit after restart my computer. The problem is solved.
