### ISSUE TITLE
how do we export the logs?

### ISSUE THREAD

**Issue by elmz87** [A9T9/RPA#46]

**Comment by elmz87** [comment]
anybody able to help?

**Comment by A9T9** [comment]
The next update will contain a [command line switch](https://a9t9.com/kantu/docs/webextensions#cmd) that allows you to export the logs. Will this solve your use case? Or do you need to export logs during non-command line runs?

**Comment by elmz87** [comment]
We are currently using the chrome extension. When is the next update?

**Comment by A9T9** [comment]
Released! See https://a9t9.com/kantu/docs/webextensions#cmd

savelog=filename.txt - This saves the log (content of the Log tab) plus a header status header as a text file once the macro has completed. The log is saved whether the run was successful or not. The calling script (e. g. Batch file, Python or Powershell) can check for the existence of this file to make sure the macro run completed). The first line of the log file is always the status of the macro run (error or success, and the error message, if any).
