### ISSUE TITLE
Open command appending first open URL to all following open commands

### ISSUE THREAD

**Issue by 01nfinity** [A9T9/RPA#47]
I created a Macro, exported it to "HTML with autorun".  Then when I launch the file and run it the macro then takes the first open command target URL and appends it to every other open command target URL in the Macro.  Is this a bug or is there something I need to change to correct this behavior? I'm very new to Kantu and selenium IDE so forgive me if I've missed something.  Any assistance you can provide would be greatly appreciated. 

`{
  "CreationDate": "2018-3-29",
  "Commands": [
    {
      "Command": "open",
      "Target": "https://meraki.cisco.com",
      "Value": ""
    },
    {
      "Command": "clickAndWait",
      "Target": "link=Products",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "30000",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "link=Solutions",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "30000",
      "Value": ""
    },
    {
      "Command": "open",
      "Target": "https://meraki.cisco.com/https:/www.cnn.com",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "30000",
      "Value": ""
    },
    {
      "Command": "clickAndWait",
      "Target": "link=World",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "30000",
      "Value": ""
    },
    {
      "Command": "clickAndWait",
      "Target": "id=logo",
      "Value": ""
    },
    {
      "Command": "open",
      "Target": "https://meraki.cisco.com/https:/www.youtube.com/watch?index=2&list=PLTVCI_tE32rS41jiv4EcoSjZqHoRxbPIy&v=o9JaTq7M8F8",
      "Value": ""
    },`

**Comment by 01nfinity** [comment]
You can close this.  After further reading of the "open" command, I realized the HTML with autostart export applies the first open command to the baseurl variable which explains this behavior.  I just remove the base URL from the exported HTML code and it works as I want it to.

**Comment by A9T9** [comment]
fixed now, too.
