### ISSUE TITLE
pause resume jumps back to first line of macro if in Test Suite

### ISSUE THREAD

**Issue by peterpeterone** [A9T9/RPA#48]
i have a Pause(0) line in my Macro.
when i run the Macro as standalone Macro, there is no problem: it pauses at the Pause line, and when i Resume, macro continues to run from that line onward.
however, if i put the same Macro inside a Test Suite and run the Test Suite as a series of Macros (either right-click the Suite folder and "Play" or right-click the Macro and "replay from here"), when i resume the Pause, macro jumps back to the first line of code of that Macro and start all over again.
is this a bug and can it be fixed so that macro resumes from the Pause line when it's run inside a Test Suite?
thank you.
peter

Chrome:  Version 65.0.3325.181 (Official Build) (64-bit)
Kantu for Chrome: version 2.6.0
Macro code:
{
  "CreationDate": "2018-4-1",
  "Commands": [
    {
      "Command": "echo",
      "Target": "1",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "",
      "Value": ""
    },
    {
      "Command": "echo",
      "Target": "2",
      "Value": ""
    }
  ]
}

**Comment by A9T9** [comment]
We confirmed the issue. Thanks for reporting it! => It will be fixed asap.

**Comment by A9T9** [comment]
fixed with v2.7.1, but now the test suite stops after this macro. This remainig issue will be fixed asap.

**Comment by peterpeterone** [comment]
works great! thank you so much!
