### ISSUE TITLE
How refresh a page each 60 seconds?

### ISSUE THREAD

**Issue by johnfelipe** [A9T9/RPA#51]
How refresh a page each 60 seconds?

**Comment by A9T9** [comment]
You can use the [Selenium IDE Refresh command](https://a9t9.com/kantu/docs/webextensions/selenium-ide/refresh), plus a [60s pause](https://a9t9.com/kantu/docs/webextensions/selenium-ide/pause) (note that 60s = 60000ms, so it is pause 60000) and then run everything in a loop or create an endless loop inside a macro with gotoif or while, just like here: https://a9t9.com/kantu/docs/webextensions/selenium-ide/while
