### ISSUE TITLE
error when i use Type command with a "+" sign in the value string:

### ISSUE THREAD

**Issue by peterpeterone** [A9T9/RPA#54]
i got the following error when i use Type command with a "+" sign in the value string:
**[error] in "+", invalid modifier:**
at first i was thinking it's some temporarily or corrupted cache problem so i cleared chrome cache and re-installed the Kantu extension, but i still get error.
it worked without errors before, i think the error started popping up today. was there a version update today / yesterday that might be related?
i just ran the same script on Kantu version 2.7.1 using another Chrome user and it worked without errors.

Kantu extension version with this error: 2.8.0
Chrome version: Version 66.0.3359.139 (Official Build) (64-bit)
Windows 10 Home Version 1511

Macro:
{
  "CreationDate": "2018-4-29",
  "Commands": [
    {
      "Command": "open",
      "Target": "https://www.google.com/",
      "Value": ""
    },
    {
      "Command": "storeEval",
      "Target": "String(\"a+b\");",
      "Value": "tempStr"
    },
    {
      "Command": "echo",
      "Target": "${tempStr}",
      "Value": ""
    },
    {
      "Command": "type",
      "Target": "id=lst-ib",
      "Value": "${tempStr}"
    }
  ]
}

please let me know how it goes. thank you!
peter

**Comment by peterpeterone** [comment]
a little more info :

**Comment by A9T9** [comment]
This issue is partially fixed with V2.8.2, more updates soon.
