### ISSUE TITLE
is kantu webextension for chrome still opensource?

### ISSUE THREAD

**Issue by jesg** [A9T9/RPA#55]
when looking closer i noticed that the version in my browser is `2.8.5` while the most recent version on github is `2.3.0`.

do you plan on releasing the source code still?  or is this project effectively closed source now?

i'm asking because i'd like to debug some edge cases that do not work for me.   i need the source code to debug properly.

**Comment by A9T9** [comment]
The source code is always directly inside the Kantu extension. If you find bugs/edge cases, please let us know. (If you need, I can also email you a snapshot of the internal repo, just email team AT a9t9.com )

V2.3.0 is GPL licensed. For the newer versions we are still undecided what license to use, thus the delay with updating this repo.
