### ISSUE TITLE
Latest Kantu for Chrome times out when finding elements that are visible

### ISSUE THREAD

**Issue by beaglecodes** [A9T9/RPA#56]
This used to work, but no longer does. The beginning of my script:

`{
  "CreationDate": "2018-5-6",
  "Commands": [
    {
      "Command": "open",
      "Target": "https://www.topcashback.com/hotel/",
      "Value": ""
    },
    {
      "Command": "store",
      "Target": "false",
      "Value": "!WaitForVisible"
    },
    {
      "Command": "click",
      "Target": "id=ctl00_GeckoTwoColPrimary_merchantPnl_hypBtnCashback",
      "Value": ""
    },
    {
      "Command": "pause",
      "Target": "2000",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "id=ctl00_BodyLast_lBtnContinue",
      "Value": ""
    },`

Error: time out when looking for element 'id=ctl00_BodyLast_lBtnContinue' 
even though I am staring right at the button (it's visible)

**Comment by A9T9** [comment]
Hmm, in my test I can really not find element 'id=ctl00_BodyLast_lBtnContinue' in the page source. Can you send a screenshot where you see it?

**Comment by beaglecodes** [comment]
Thanks for the fast response! Here is the element:

![screenshot 2018-05-06 15 50 09](https://user-images.githubusercontent.com/22315097/39678648-39285e74-5145-11e8-8676-1c7014083c90.jpg)

**Comment by A9T9** [comment]
Do you still have this issue after the recent updates?

**Comment by beaglecodes** [comment]
Thanks for your response, I just tried it again with the latest version, and it is still occurring. :( Everything still looks the same.

If you would like to try, the website is https://www.topcashback.com/hotel/
Please click the red "Get Cashback Now" button, and then click the "Ok, continue" button after that.

**Comment by A9T9** [comment]
If this still is an issue, please post in the forum at https://forum.a9t9.com/
