### ISSUE TITLE
visionFind - not always accurate and some suggestions

### ISSUE THREAD

**Issue by cwpm** [A9T9/RPA#58]
I'm loving the new feature of VisionFind and has been what I've been wanting for so long.

So my ideal is to run have screenshots and compared them at various stages to a master screenshot to ensure that making a change in one place, doesn't have consequences on another.

So I've been running some tests on a website: https://www.ramsdens.co.uk/about
Highlighting the breadcrumb, another on the right sidebar of the page list, and the logo.
Using the same screen resolution and browser, if I use the Find command ( next to Select button) with the screen in the same view it highlights and shows 0.97-ish. But when running the command separately and it jerks up and down and only finds 1 of the 3 (the 1 being the logo). The rest it doesn't find.

I have tried lowering the match rate to 0.75 but it still doesn't find, and I'm reluctant to lower it anymore because on a standard find it show it at 0.97. 

So it's feeling like it's not working as intended or may need to be reviewed.
I'm happy to share the script, and share the partial screenshots, if that'll help?

I'm really excited for this feature. 

Some slight suggestions. If when you do a screenshot using VisionFind and have the reference, go the Value be used as reference like a set name?

If it can do a full screen of the page and highlight as well like these tools, that would be fantastic!
https://online-image-comparison.com/
https://www.diffchecker.com/image-diff

Actually show whats different compared to an original.

**Comment by A9T9** [comment]
> I'm happy to share the script, and share the partial screenshots, if that'll help?

Yes, please do, this will help a lot. And sorry for the late response, we had been busy with the new release. Note that visionFind is now called visualSearch.

**Comment by A9T9** [comment]
Closing as no reponse (feel free to reopen if needed)
