### ISSUE TITLE
No Tab with id : xxx

### ISSUE THREAD

**Issue by swetaCode** [A9T9/RPA#59]
Theres a popup, I attach a file on the popup and then click on the close button, which automatically refreshes the parent window. But While automating Kantu says , "No tab with id: 409" . and doesnot focus back on the parent window. so no actions on parent window afterwards are recorded.

**Comment by A9T9** [comment]
Do you have a macro or website link to recreate the issue?

**Comment by A9T9** [comment]
Closing as no response... => feel free to reopen if needed
