### ISSUE TITLE
New tab problem

### ISSUE THREAD

**Issue by pdent1** [A9T9/RPA#60]
I am running Kantu and trying to open a new tab 

`{
  "CreationDate": "2018-7-25",
  "Commands": [
    {
      "Command": "store",
      "Target": "true",
      "Value": "!ErrorIgnore"
    },
    {
      "Command": "csvRead",
      "Target": "extractff.csv",
      "Value": ""
    },
    {
      "Command": "store",
      "Target": "${!COL1}",
      "Value": "!csvLine"
    },
    {
      "Command": "selectWindow",
      "Target": "tab=open",
      "Value": "http://google.com"
    },
    {
      "Command": "waitForPageToLoad",
      "Target": "0",
      "Value": "0"
    },
    {
      "Command": "open",
      "Target": "${!COL1}",
      "Value": "downloadlink"
    },
    {
      "Command": "waitForPageToLoad",
      "Target": "0",
      "Value": "0"
    },
    {
      "Command": "pause",
      "Target": "5000",
      "Value": ""
    }
  ]
}`

The csv file has multiple URLS. When SelectWindow tab=open hits, instead of opening 1 tab it opens two. Also it seems I can't have an about:blank page as active tab, why I call for a new tab at google.com as after each loop tab is closed automatically. If I am at a new blank tab this is the URL it goes to rather than the one from the csv. chrome-extension://gcbalfbdmfieckjlnblleoemohcganoc/!%7BCOL1%7D

**Comment by A9T9** [comment]
Discussion continues in forum: https://forum.a9t9.com/t/keep-getting-new-tab-error/344/7
