### ISSUE TITLE
Kantu should not start until user want it.

### ISSUE THREAD

**Issue by senpl** [A9T9/RPA#61]
On page that it should not even be (like gmail) it showes that log in console log that error. I think Kantu should not run anything when it not records in record mode.

content_script.js:6777 Uncaught (in promise) Error: csPostMessage: timeout 60000 ms
    at content_script.js:6777
(anonymous) @ content_script.js:6777
content_script.js:6812 Uncaught (in promise) TypeError: Cannot read property 'postMessage' of undefined
    at content_script.js:6812

**Comment by teamdocs** [comment]
You mean you are in Gmail and not using Kantu at all (since loading Gmail page), and you still see these log errors? If so, do you always see this, or does it only happen "sometimes"?

> I think Kantu should not run anything when it not records in record mode.

Yes, that is how it should be. Everything else would be a bug.

**Comment by A9T9** [comment]
You mean you are in Gmail and not using Kantu at all (since loading Gmail page), and you still see these log errors? If so, do you always see them, or does it only happen "sometimes"?

> I think Kantu should not run anything when it not records in record mode.

Yes, that is how it should be. Everything else would be a bug.

**Comment by senpl** [comment]
Yes, exactly. Every time I am not using Kantu and go to gmail(that new one which is now standard) I got that error after defined time (I think You could reproduce it with even shorter delay). Maybe interacting with gmail(like checking inbox for ex. got something to do with that.

**Comment by A9T9** [comment]
Does anyone see the same issue as well? Maybe with other (less complex) websites than Gmail?

**Comment by lanfeust21** [comment]
i have the same error

**Comment by A9T9** [comment]
Closing this, as we use the [forum ](https://forum.a9t9.com/) now to track bugs and feature requests.

**Comment by senpl** [comment]
It would be nice to give direct link for tracked bug. Even nicer would be copy existing issues into forum.

**Comment by A9T9** [comment]
Hi, since you are "here"... can you please test if you still see the issue even in the latest release? We still have a problem recreating this issue.

**Comment by senpl** [comment]
Problem still exist:  
      e.source.postMessage(_extends({}, tpl, {
content_script.js:30810 Uncaught (in promise) TypeError: Cannot read property 'postMessage' of undefined
    at content_script.js:30810
This point on your extension. Simply not start anything until user at least show  recording popup.
On latest version(3.8.8). If U need more details let me know.

**Comment by A9T9** [comment]
We are coming back to this issue. => Does the issue still show in the latest version? And if so, can you please post instructions on how to recreate this issue?

**Comment by A9T9** [comment]
For updates to this ticket, please report bugs here: https://forum.ui.vision/c/kantu/bug-reports

(Most users prefer a forum over GitHub, that is why we use the forum instead of tickets. This also allows users to search everything in one place).
