### ISSUE TITLE
Page down

### ISSUE THREAD

**Issue by jappa91** [A9T9/RPA#62]
Hey can you tell me what i do wrong?

i need to scroll down to the bottom from this page https://www.twitch.tv/prime.

tried to select every element or with selectframe. but it doesnt matter what i do i cant go to the bottom of the page, tried KEY_DOWN (Navigation Down) and KEY_PGDN / KEY_PAGE_DOWN (Page down).

can you point me to a solution?

**Comment by A9T9** [comment]
Hi, 

thanks for your question. For Kantu tech support, please post your question in our Kantu forum at https://forum.a9t9.com/

The Github ticket system is best used for bug tracking. The forum is a better place for discussions.

Our Kantu community forum is monitored by our tech support and active Kantu users. So it would be great if you can quickly sign up for the forum, and then simply copy and paste your current question as a new topic in the forum. We make sure that every topic gets a reply.

I hope to see you at https://forum.a9t9.com/ :-)

**Comment by A9T9** [comment]
That said
