### ISSUE TITLE
Kantu gets slower and slower the longer the script is running

### ISSUE THREAD

**Issue by TFD777** [A9T9/RPA#64]
Hello, I've been using Kantu for a while and I was really happy when the IPC bug has been solved, because I was finally able to run scripts without worrying that they will hang, however, recently I have discovered another huge issue. 
It seems that whenever you run the script and leave it for an hour or more - it gets super slow, up to 10 times slower than it is on the initial start. I've created a simple performance script that clearly shows the issue:

```
{
  "CreationDate": "2018-10-21",
  "Commands": [
    {
      "Command": "store",
      "Target": "fast",
      "Value": "!replayspeed"
    },
    {
      "Command": "store",
      "Target": "Iteration",
      "Value": "!csvLine"
    },
    {
      "Command": "store",
      "Target": "Speed in seconds",
      "Value": "!csvLine"
    },
    {
      "Command": "csvSave",
      "Target": "performance_test",
      "Value": ""
    },
    {
      "Command": "store",
      "Target": "0",
      "Value": "i"
    },
    {
      "Command": "store",
      "Target": "10000",
      "Value": "j"
    },
    {
      "Command": "label",
      "Target": "START",
      "Value": ""
    },
    {
      "Command": "storeEval",
      "Target": "Date.now()",
      "Value": "start"
    },
    {
      "Command": "storeEval",
      "Target": "${i}+1",
      "Value": "i"
    },
    {
      "Command": "storeEval",
      "Target": "(Date.now()-${start})/1000",
      "Value": "end"
    },
    {
      "Command": "store",
      "Target": "${i}",
      "Value": "!csvLine"
    },
    {
      "Command": "store",
      "Target": "${end}",
      "Value": "!csvLine"
    },
    {
      "Command": "csvSave",
      "Target": "performance_test",
      "Value": ""
    },
    {
      "Command": "echo",
      "Target": "Run time - ${end}s",
      "Value": "red"
    },
    {
      "Command": "gotoIf",
      "Target": "${i} < ${j}",
      "Value": "START"
    }
  ]
}
```

Just leave it until it times out (15min), then open the "performance_test.csv" file and check the initial speed values and then compare with the values in the end of the script.

In my case, the average speed for the first 100 iterations was 0.324s, while the average speed for the last 100 iterations was 0.551s, which is 70% slower than it was in the beginning **JUST AFTER 15 MINUTES OF RUNTIME**. So you can only imagine what happens when you leave the script for an hour or longer. 

I really hope that this data will help you to fix this issue as soon as possible and also thank you so much for your great work on creating one of the best automation tools currently available. 👍

**Comment by TFD777** [comment]
@A9T9 we really need your help ❤️

**Comment by NytronX** [comment]
Showstopping issue. Also having the macro randomly get stuck which happens more often as this slowdown issue occurs. Pausing and unpausing causes it to start working again. Until these issues are sorted out, there should be a setting in Kantu that allows it to automatically restart itself after x seconds. Same goes with pause and unpause.

**Comment by teamdocs** [comment]
> Until these issues are sorted out, there should be a setting in Kantu that allows it to automatically restart itself after x seconds. Same goes with pause and unpause.

Actually, there is: with the kantu command line you have full control over kantu, and can close it (and chrome) if something goes wrong: see https://forum.a9t9.com/t/freeze-or-non-responsive-issue/1131/2 and https://github.com/A9T9/Kantu/tree/master/command-line/

**Comment by A9T9** [comment]
> Until these issues are sorted out, there should be a setting in Kantu that allows it to automatically restart itself after x seconds. Same goes with pause and unpause.

Actually, there is: with the kantu command line you have full control over kantu, and can close it (and chrome) if something goes wrong: see https://forum.a9t9.com/t/freeze-or-non-responsive-issue/1131/2 and https://github.com/A9T9/Kantu/tree/master/command-line/

**Comment by A9T9** [comment]
Closing this, as we use the [forum ](https://forum.a9t9.com/) now to track feature request.
