### ISSUE TITLE
Kantu XModules does not honor !REPLAYSPEED

### ISSUE THREAD

**Issue by JESii** [A9T9/RPA#65]
I upgraded to XModules; after restarting the browser, my scripts no longer pause between commands -- they just run as FAST as possible.

I've set replaySpeec = MEDIUM and SLOW in both the UI/settings and in a command in the script... nothing works to slow things down, so now my scripts are unusable because they overrun the browser.

**Comment by A9T9** [comment]
Strange. Is this in Chrome? I just retested and it works for me. See this screencast: https://www.screencast.com/t/Uw0TC54sgzW

**Comment by A9T9** [comment]
I close this ticket. We can continue the discussion in the forum at https://forum.a9t9.com/t/kantu-script-running-too-fast/998

**Comment by JESii** [comment]
Yes; it's in Chrome - Version 70.0.3538.67 (Official Build) (64-bit) - on MacOS HighSierra 10.13.6.
I'll go back to the forum, although not too much help so far;
