### ISSUE TITLE
Centos7 libstdc++.so.6  install issues 

### ISSUE THREAD

**Issue by IanWardell** [A9T9/RPA#66]
install script doesnt work:
I get the following error when i try to run the install script components individually. 
./kantu-file-access-host: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./kantu-file-access-host)
./kantu-file-access-host: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./kantu-file-access-host)
./kantu-file-access-host: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./kantu-file-access-host)

**Comment by A9T9** [comment]
Currently we only officially support Ubuntu 18.04

**Comment by IanWardell** [comment]
> Currently we only officially support Ubuntu 18.04

Ah that makes sense. What is stopping RHEL/CENTOS support, technical roadblock or time roadblock?

**Comment by A9T9** [comment]
Time ;-) 

RHEL/CENTOS is on our todo list for later this year.
