### ISSUE TITLE
Kaptu stopped with error panel tab id recorded expired! 

### ISSUE THREAD

**Issue by AndreyVys** [A9T9/RPA#70]
I use kaptu with raspberry pie and chromium. I make html and start from command line
"chromium-browser script.html" If chromium is open everything is ok. If i reboot rpie html page is opened and after some time i get window with error "panel tab id recorded expired!" So kaptu can`t start script automaticaly. But after close window i can start script by manual.

**Comment by A9T9** [comment]
Please report bugs here: https://forum.ui.vision/c/kantu/bug-reports

(Most users prefer a forum over GitHub, that is why we use the forum instead of tickets).
