### ISSUE TITLE
allow whitespace in json

### ISSUE THREAD

**Issue by colinlieberman** [A9T9/RPA#71]
Hi, I'm loving this tool, thanks!

Would it be possible to allow whitespace in macro & testsuite .json files? This would help quite a bit with readability.

We're checking these files into version control, symlinked to the XModule filesytem storage location, so we're making limited use of your IDE and editing the files in our own text editors. Having visual whitespace would be super handy

Thanks!

**Comment by A9T9** [comment]
Hi, do you have an example of what kind of white space you have in mind?

Also, kantu has a [comment command](https://a9t9.com/kantu/docs/selenium-ide/comment). Does this solve it?

Another useful command to help with readability and code reuse is the new [run command](https://a9t9.com/kantu/docs/selenium-ide/run).

**Comment by colinlieberman** [comment]
Here are two screen shots - one with how whitespace is currently enforced, and one with allowed whitespace between commands, allowing the creation of visual blocks, making it easy to segment things, find them, etc

![Screen Shot 2019-04-08 at 11 50 49](https://user-images.githubusercontent.com/1573369/55749051-f2afa380-59f4-11e9-908e-a8054ecf438f.png)

![Screen Shot 2019-04-08 at 11 54 25](https://user-images.githubusercontent.com/1573369/55749156-25599c00-59f5-11e9-99c4-096f2de80794.png)

Thanks

**Comment by A9T9** [comment]
Please report bugs here: https://forum.ui.vision/c/kantu/bug-reports

(Most users prefer a forum over GitHub, that is why we use the forum instead of tickets).
