### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by ainthek** [A9T9/RPA#73]
BUIDLING on OSX

$ npm run build
$ node -v
v8.11.1
$ npm -v
5.6.0    

> chrome-extension@1.0.0 build .../workspaces/Kantu
> cross-env NODE_ENV=production BROWSER=chrome webpack --mode production --config webpack.prod.config.js

.../workspaces/Kantu/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (.../workspaces/Kantu/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at .../workspaces/Kantu/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (.../workspaces/Kantu/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

BTW:

npm ls prints

npm ERR! peer dep missing: webpack@^2.2.0 || ^3.0.0, required by webpack-dev-server@2.11.5
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.1, required by react-slick@0.15.4
npm ERR! peer dep missing: react-dom@^0.14.0 || ^15.0.1, required by react-slick@0.15.4
npm ERR! peer dep missing: webpack@^1.0.0 || ^2.0.0 || ^3.0.0, required by webpack-dev-middleware@1.12.2

**Comment by ainthek** [comment]
experimenting with dependecies in package.json and chaning to
"webpack": "^4.20.2",
 "webpack-cli": "^3.1.1",

seemed to help with this error but now there are other errors now:

ERROR in ./src/common/imagesearch/adaptor.ts
Module not found: Error: Can't resolve '../../../imagesearch-testextension/src/ts/image-helper' in '.../workspaces/Kantu/src/common/imagesearch'
 @ ./src/common/imagesearch/adaptor.ts 5:23-88
 @ ./src/ext/bg.js

**Comment by TroyLDay** [comment]
Confirmed. imagesearch-testextension directory is not in the repo.

**Comment by A9T9** [comment]
>  imagesearch-testextension 

This code is not needed. As the name suggests, it is just an internal helper extension. That said, there is a build issue with the repo code here and we will look into it.
