### ISSUE TITLE
execution just stops running

### ISSUE THREAD

**Issue by condovacay** [A9T9/RPA#75]
Any update on this? It says closed but my macro locks up like the issues raised above. Code loops through 16 records on a page and then does 16 inserts/submits on a webpage. the macro locks up/freezes at very random places throughout the script. I can also say that when I put the execution speed at FAST, it runs slower and slower as the macro progresses. occasionally the macro restarts on its own but rarely. the pc does not freeze, just the execution of the macro.

**Comment by A9T9** [comment]
Fixed
