### ISSUE TITLE
onClick handler alter page behavior

### ISSUE THREAD

**Issue by PapsOu** [A9T9/RPA#76]
I'm using Kantu for chrome (chromium).

When the extension is active, click events throws the following error.

**console out :**
```
content_script.js:3711 Uncaught TypeError: Cannot read property 'recordClickType' of undefined
    at HTMLDocument.onClick (content_script.js:3711)
onClick @ content_script.js:3711
```

**content_script.js:3711 :**
```
_common_log__WEBPACK_IMPORTED_MODULE_11___default()('onClick, switch  case', state.config.recordClickType);
```

It breaks the scripts on the web page, so that is very annoying (I must disable Kantu extension in order to have a working web page)

**Comment by A9T9** [comment]
Do you have a test website for us?

**Comment by PapsOu** [comment]
Try this current page with Chromium

![20190704-143610](https://user-images.githubusercontent.com/5792207/60667168-228e0c00-9e69-11e9-8092-699713012c2a.png)

**Comment by A9T9** [comment]
Solved
