### ISSUE TITLE
Showing error: Macro did not complete withing the time given. Even if it is completed 

### ISSUE THREAD

**Issue by kudeshiyah** [A9T9/RPA#78]
I am trying to run kantu macro using python script PlayAndWait function. but it is not able to detect that macro is finished. It is showing the following msg
Macro did not complete withing the time given

Even if macro is completed

give timeout_seconds 120
original macro finished in 9.97 seconds

**Comment by A9T9** [comment]
Please report issues in the [RPA software forum](https://forum.ui.vision/).
