### ISSUE TITLE
Multiple kantu windows opening 

### ISSUE THREAD

**Issue by loryculaire** [A9T9/RPA#79]
Hi,

When I launch a macro, several windows usually open. From 2 to many : 

![Capture d’écran 2019-08-05 à 15 58 20](https://user-images.githubusercontent.com/2540518/63796768-f17d0580-c906-11e9-9909-041b29f4ff9c.png)

I have the impression that they run at the same time but with a few second time lag, preventing the macro to execute itself well.

The url is whitelisted and it's reproductible everytime. 
I'm on Chrome Version 76.0.3809.100 (Build officiel) (64 bits)
The Macro is served through a server. 
In the URL there is the parameter direct=1

Should I put this issue on the forum too ?

Thank you for your help

**Comment by A9T9** [comment]
Solved
