### ISSUE TITLE
[Feature request] Automatic HAR export

### ISSUE THREAD

**Issue by BenoitPoulet** [A9T9/RPA#80]
Hello,

For web testing it can bu useful to have an HAR file for each page loaded by the macros.

In case of failure, we can easily see which element can be the root cause by looking into the HAR.

We can analyse HAR file with externals tools, like :
http://www.softwareishard.com/har/viewer/
https://toolbox.googleapps.com/apps/har_analyzer/

Regards.

**Comment by A9T9** [comment]
For feature suggestions please use the [RPA software forum](https://forum.ui.vision/).
