### ISSUE TITLE
Kantu test stops randomly when executing loop commands

### ISSUE THREAD

**Issue by LucaAlimandi** [A9T9/RPA#84]
@LucaAlimandi Do you have a test case for us? A small macro + CSV file that shows the issue will be great. As soon as we can recreate the issue, we can fix it.

_Originally posted by @A9T9 in https://github.com/A9T9/Kantu/issues/35#issuecomment-543140363_

**Comment by LucaAlimandi** [comment]
I open a new issue as it seems that the previous one (#35) has been closed, so maybe it is not in working progress state...

Anyway I note a similar issue with Selenium IDE, but in that case it has to do with the downloading of files (se the last post in #35 issue).

But in both situations the log reports that the page (or the tab, in Kantu) is not accessible. Maybe this can help you to address the issue...

Let me know, please!

Thank you very much!

LA

**Comment by A9T9** [comment]
Please report issues in the [RPA software forum](https://forum.ui.vision/).
