### ISSUE TITLE
[QUESTION] Do exported tests run on an other Kantu configuration?

### ISSUE THREAD

**Issue by MMeunierSide** [A9T9/RPA#86]
Hey,

I'm fairly new to Kantu (and Selenium) and I'm trying to implement it in the company I work in. We would like to automate Kantu tests in a Jenkins Pipeline. Everything is set up perfectly and chrome starts on our server but, the exported test (html file) from my computer doesn't run. It starts and display the table of commands in html but doesn't execute any of them.

Thanks for your help,
Cordially,
Matthieu

**Comment by A9T9** [comment]
Please report issues in the [RPA software forum](https://forum.ui.vision/).
