### ISSUE TITLE
sendKeys

### ISSUE THREAD

**Issue by A9T9** [A9T9/RPA#9]
similar to Type, but does not erase fields

Special keys for SendKey and Type

User will use them like a variable with ${KEY_ENTER}

o	KEY_LEFT (Navigation Left)
o	KEY_UP (Navigation Up)
o	KEY_RIGHT (Navigation Right)
o	KEY_DOWN (Navigation Down)
o	KEY_PGUP / KEY_PAGE_UP (Page up)
o	KEY_PGDN / KEY_PAGE_DOWN (Page down)

o	KEY_BKSP / KEY_BACKSPACE (Backspace)
o	KEY_DEL / KEY_DELETE (Delete)
o	KEY_ENTER (Enter)

o	KEY_INS / KEY_INSERT (Insert)

o	KEY_TAB (Tab)

Any other special key **really** needed? (If so, please mention why/for what)

**Comment by A9T9** [comment]
done, https://a9t9.com/kantu/docs/webextensions/selenium-ide/sendkeys-type

**Comment by macem** [comment]
Yes for example KEY_ESC

**Comment by Meowdoleon** [comment]
I would also love a KEY_SPACE
