### ISSUE TITLE
Can't start or build project

### ISSUE THREAD

**Issue by Lanbasara** [A9T9/RPA#93]
Dear owner,
         Very great project! But when I clone this project and try to start this project on local, it reports many errors. 
         What I have done is as below:
         1. git clone 2. npm i (in this step, npm reports some errors, about dependencies) 
         3. I update some dependencies as pull requests recommended. But it doesn't help.
         So, How Can I run the project? Thanks a lot for your help.

**Comment by A9T9** [comment]
Updated

**Comment by qhc-git** [comment]
I can't run start also,when I run npm i ,it reports many errors,the node version I use is 16.14.0,so I change my node version to 12.22.10,it finally success run npm i with some warn and no err.But when I try to npm run start,it still report many error.
